image: Visual Studio 2022
# https://ci.appveyor.com/tools/encrypt
environment:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  SyncfusionLicense:
    secure: POvs0RsENyxFwe/Lt6vwOI+pSML3OtDui2rtGsu7qRCYy2eF/HIYGKQ7XvbNUz6mUHIbQ/NgjgxkiJNajglmFW7LHkfWsT9PpHcloQ1+S91WZictJJYpx2RqbxVbtOHl
build_script:
- pwsh: |
    Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
    ./dotnet-install.ps1 -JSonFile src/global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
- dotnet build src --configuration Release
- dotnet test src --configuration Release --no-build --no-restore
test: off
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: nugets\*.nupkg